apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector: {{- toYaml .Values.rabbitmq.nodeSelector | nindent 8 }}        
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.rabbitmq.image.repository }}:{{ .Values.rabbitmq.rabbitmq.image.tag
          | default .Chart.AppVersion }}
          ports:
            - containerPort: 5672
              name: rabbitmq-amqp
            - containerPort: 15672
              name: rabbitmq-http
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ quote .Values.rabbitmq.rabbitmq.env.rabbitmqDefaultUser }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ quote .Values.rabbitmq.rabbitmq.env.rabbitmqDefaultPass }}
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: rabbitmq-enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
      volumes:
        - name: rabbitmq-enabled-plugins
          configMap:
            name: rabbitmq-enabled-plugins
            items:
              - key: rabbitmq_enabled_plugins
                path: enabled_plugins